.TH "<errno.h>: System Errors" 3 "15 Dec 2017" "Version 2.0.0" "avr-libc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
<errno.h>: System Errors \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBEDOM\fP   33"
.br
.ti -1c
.RI "#define \fBERANGE\fP   34"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBerrno\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.PP
.nf
 #include <errno.h>
.fi
.PP
.PP
Some functions in the library set the global variable \fCerrno\fP when an error occurs. The file, \fC<\fBerrno.h\fP>\fP, provides symbolic names for various error codes. 
.SH "Define Documentation"
.PP 
.SS "#define EDOM   33"Domain error. 
.SS "#define ERANGE   34"Range error. 
.SH "Variable Documentation"
.PP 
.SS "int \fBerrno\fP"
.PP
Error code for last error encountered by library. The variable \fCerrno\fP holds the last error code encountered by a library function. This variable must be cleared by the user prior to calling a library function.
.PP
\fBWarning:\fP
.RS 4
The \fCerrno\fP global variable is not safe to use in a threaded or multi-task system. A race condition can occur if a task is interrupted between the call which sets \fCerror\fP and when the task examines \fCerrno\fP. If another task changes \fCerrno\fP during this time, the result will be incorrect for the interrupted task. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for avr-libc from the source code.
