/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serial4j_core_errno_NativeErrno */

#ifndef _Included_com_serial4j_core_errno_NativeErrno
#define _Included_com_serial4j_core_errno_NativeErrno
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getBadFileDescriptorErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getBadFileDescriptorErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getBrokenPipeErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getBrokenPipeErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getFileAlreadyOpenedErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getFileAlreadyOpenedErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getFileIsDirectoryErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getFileIsDirectoryErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getFileTableOverflowErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getFileTableOverflowErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getFileTooLargeErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getFileTooLargeErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getInputOutputErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getInputOutputErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getInterruptedSystemCallErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getInterruptedSystemCallErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getInvalidArgumentErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getInvalidArgumentErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getInvalidPortErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getInvalidPortErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getNoAvailableTtyDevicesErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getNoAvailableTtyDevicesErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getNoSpaceLeftErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getNoSpaceLeftErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getNoSuchDeviceErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getNoSuchDeviceErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getNoSuchFileErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getNoSuchFileErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getNotTtyDeviceErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getNotTtyDeviceErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getOperationFailedErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getOperationFailedErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getPermissionDeniedErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getPermissionDeniedErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getReadOnlyFileSystemErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getReadOnlyFileSystemErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getTooManyOpenedFilesErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getTooManyOpenedFilesErrno
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_errno_NativeErrno
 * Method:    getTryAgainErrno
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_errno_NativeErrno_getTryAgainErrno
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
