/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serial4j_core_serial_NativeTerminalDevice */

#ifndef _Included_com_serial4j_core_serial_NativeTerminalDevice
#define _Included_com_serial4j_core_serial_NativeTerminalDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    setupJniEnvironment0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_setupJniEnvironment0
  (JNIEnv *, jclass);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    setTerminalControlFlag
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_setTerminalControlFlag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    setTerminalLocalFlag
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_setTerminalLocalFlag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    setTerminalInputFlag
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_setTerminalInputFlag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    setTerminalOutputFlag
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_setTerminalOutputFlag
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    getTerminalControlFlag
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_getTerminalControlFlag
  (JNIEnv *, jobject);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    getTerminalLocalFlag
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_getTerminalLocalFlag
  (JNIEnv *, jobject);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    getTerminalInputFlag
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_getTerminalInputFlag
  (JNIEnv *, jobject);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    getTerminalOutputFlag
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_getTerminalOutputFlag
  (JNIEnv *, jobject);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    setReadConfigurationMode0
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_setReadConfigurationMode0
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    getReadConfigurationMode0
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_getReadConfigurationMode0
  (JNIEnv *, jobject);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    getErrno0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_getErrno0
  (JNIEnv *, jobject);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    fetchSerialPorts0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_fetchSerialPorts0
  (JNIEnv *, jobject);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    getBaudRate0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_getBaudRate0
  (JNIEnv *, jobject);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    writeData0
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_writeData0
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    readData0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_readData0
  (JNIEnv *, jobject);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    writeBuffer0
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_writeBuffer0
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    readBuffer0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_readBuffer0
  (JNIEnv *, jobject);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    openPort0
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_openPort0
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    initTermios0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_initTermios0
  (JNIEnv *, jobject);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    setBaudRate0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_setBaudRate0
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_serial4j_core_serial_NativeTerminalDevice
 * Method:    closePort0
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_serial4j_core_serial_NativeTerminalDevice_closePort0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
