/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_serial4j_example_HelloSerial4J */

#ifndef _Included_com_serial4j_example_HelloSerial4J
#define _Included_com_serial4j_example_HelloSerial4J
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serial4j_example_HelloSerial4J
 * Method:    testJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_serial4j_example_HelloSerial4J_testJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
